- name: Configure repo name
  ansible.builtin.template:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis service
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: Update {{COMPONENT}} listening address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Start the {{COMPONENT}} service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes




