- name: Install nginx service
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Update systemd service
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Update Nginx service
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start the {{COMPONENT}} service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

