- name: Fail if RABBITMQ_USER_PASSWORD does not exist
  ansible.builtin.fail:
    msg: Needed RABBITMQ_USER_PASSWORD variable
  when: RABBITMQ_USER_PASSWORD is undefined

- name: Configure yum repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Install ERLANG and RABBITMQ
  ansible.builtin.yum:
    name:
      - https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm
      - rabbitmq-server
    state: installed

- name: Start the {{COMPONENT}} service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes
    daemon_reload: yes


- name: Create roboshop user and give tags and permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{RABBITMQ_USER_PASSWORD}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator






