- name: Configure the Elastic.repo template
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: installed