- name: Configure the Elastic search template
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Restart elk
  ansible.builtin.systemd:
    name: filebeat
    state: restarted