- name: Configure the Elastic.repo template
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Configure the filebeat template
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restart FILEBEAT
  ansible.builtin.systemd:
    name: filebeat
    state: restarted