#MYSQL_DEFAULT_PASSWORD=$(grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}')
#
#echo show databases | mysql -uroot -p"${MYSQL_PASSWORD}" &>>${LOG}
#if [ $? -ne 0 ]; then
#PRINT "Reset root password"
#echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';" | mysql  --connect-expired-password -uroot -p"${MYSQL_DEFAULT_PASSWORD}" &>>${LOG}
#CHECK_STAT $?
#fi
#
#echo show plugins | mysql -uroot -p"${MYSQL_PASSWORD}" 2>>${LOG} | grep validate_password &>>${LOG}
#if [ $? -eq 0 ]; then
#PRINT "uninstall password validate plugin"
#echo "uninstall plugin validate_password;" | mysql -uroot -p"${MYSQL_PASSWORD}" &>>${LOG}
#CHECK_STAT $?
#fi
#
#PRINT "Download schema"
#curl -s -L -o /tmp/mysql.zip https://github.com/roboshop-devops-project/mysql/archive/main.zip &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Load schema"
#cd /tmp && unzip -o mysql.zip &>>${LOG} && cd mysql-main && mysql -uroot -p"${MYSQL_PASSWORD}" <shipping.sql &>>${LOG}
#CHECK_STAT $?


- name: Fail if the MYSQL_PASSWORD does not exists
  ansible.builtin.fail:
    msg: MYSQL_PASSWORD variable is missing
  when: MYSQL_PASSWORD is undefined

- name: copy Mysql repo file
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install Mysql
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start MYSQL service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Find out what the remote machine's mounts are
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_log

- name: PRINT
  debug:
    msg: "{{mysql_log['content'] | b64decode}}"









