- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Create Application user
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: remove app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Create app location
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: directory

- name: Download and Extract {{ COMPONENT }} content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy {{ COMPONENT }} code
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/{{SUFFIX}}
    dest: "{{ APP_LOCATION }}/"
    remote_src: yes

- name: Install golang dependencies
  ansible.builtin.shell: go mod init {{ COMPONENT }} && go get && go build
  args:
    chdir: /home/roboshop/{{ COMPONENT }}

- name: Systemd setup for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd