- name: Prometheus server setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: server
  when: SETUP_TYPE == "server"

- name: Prometheus Client setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: client
  when: SETUP_TYPE == "client"
    