- name: Prometheus server configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Prometheus alerts configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/alerts.yml

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check the prometheus server is running or not
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 15