- name: Remove old file
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Download and Extracting {{ COMPONENT }} content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes