- name: Download {{ COMPONENT }} content
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp/{{ COMPONENT }}.zip


- name: Start {{ COMPONENT }} service
  ansible.builtin.service:
    name: nginx
    state: started
    enable: yes

