- name: Install Python-3
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Copy {{ COMPONENT }} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install python Dependencies
  ansible.builtin.pip:
    requirements: "{{ APP_LOCATION }}/requirements.txt"
    executable: pip3
    
- name: print
  debug:
    msg: "{{app_user}}"

#- name: Give root permissions to user and group
#  ansible.builtin.user:
#    name: roboshop
#    comment:
#    uid: USER_ID=$(id -u roboshop)
#    group: GROUP_ID=$(id -g roboshop)
##USER_ID=$(id -u roboshop)
#GROUP_ID=$(id -g roboshop)
#
#PRINT "Update ${COMPONENT} configuration"
#sed -i -e "/^uid/ c uid = ${USER_ID}" -e "/^gid/ c gid = ${GROUP_ID}" /home/roboshop/${COMPONENT}/${COMPONENT}.ini &>>${LOG}
#CHECK_STAT $?
#
#SYSTEMD

