groups:
  - name: Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:{% raw %}
          summary: "Instance Down - [{{ $labels.instance}}]"
          description: "Instance Down - [{{ $labels.instance}}]"{% endraw %}

      - alert: ServerDown
        expr: node_systemd_unit_state{exported_name="nginx.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:{% raw %}
          summary: "Server Down - [{{ $labels.exported_name}}]"
          description: "Server Down - [{{ $labels.exported_name}}]"{% endraw %}